### ISSUE TITLE
Native events cause a TS error

### ISSUE THREAD

**Issue by TheDutchCoder** [znck/vue-developer-experience#150] opened 2021-01-08 15:01 UTC
**Describe the bug**
When adding a native event handler to a component, like `click`, the plugin will throw a TS error on the props of the component.

Example:
```html
        <ActionButton
          class="w-1/3"
          :disabled="state.matches('details.waiting')"
          @click="send('SUBMIT')"
        >
          {{ state.matches('details.waiting') ? 'Loading...' : 'Send me a code' }}
        </ActionButton>
```

**To Reproduce**
1. Add a `@click` handler to a custom component (component is just a button at the root)

**Expected behavior**
TS to not check native events as props.

**Info (please complete the following information):**
 - OS MacOS 10.15.7
 - IDE VSCode
 - TypeScript Version 3.9.3
 - Vue Version: 3.0.0

**Additional context**
This might actually be due to how Vue exposes props/events, but I have no knowledge of that :)

**Comment by znck** [comment] 2021-01-08 16:12
Duplicate of #115

**Closed** 2021-01-08 16:12 UTC
Labels: bug
